from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Tuple

import httpx
from pydantic import BaseModel, Field

from app.config import Settings
from app.schemas import ReviewPlan


class _ModelAuditResponse(BaseModel):
    results: List[Dict[str, Any]] = Field(default_factory=list)
    notes: List[str] = Field(default_factory=list)


logger = logging.getLogger(__name__)


class KimiClient:
    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    @property
    def enabled(self) -> bool:
        return bool(self._settings.llm_api_key)

    async def audit(
        self,
        strategy_payload: Dict[str, Any],
        review_plan: ReviewPlan,
        page_payload: List[Dict[str, Any]],
    ) -> Tuple[List[Dict[str, Any]], List[str]]:
        if not self.enabled:
            raise RuntimeError("LLM API key is missing.")

        system_prompt = (
            "You are a professional PDF document audit agent. "
            "Audit strictly according to the user-provided strategy rules, not any demo or default rules. "
            "Use the supplied page text blocks and bounding boxes as the primary evidence source. "
            "You must return strict JSON only. "
            "Output schema: {results:[{rule_id,page,bbox[4],content,suggestion,status,severity}],notes:[string]}. "
            "For every result, bbox must be [x1,y1,x2,y2] in PDF coordinates. "
            "status must be pass or fail; severity must be low/medium/high. "
            "When failing a rule, content must explain the concrete issue and cite the relevant page evidence. "
            "When passing a rule, content must explain what evidence supports the pass."
        )
        user_payload = {
            "strategy": strategy_payload,
            "review_plan": review_plan.model_dump(),
            "document": {"pages": page_payload},
            "constraints": {
                "strict_json": True,
                "bbox_coordinate_space": "pdf",
                "follow_selected_strategy_only": True,
            },
        }

        request_body = {
            "model": self._settings.llm_model,
            "temperature": 1,
            "response_format": {"type": "json_object"},
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(user_payload, ensure_ascii=False)},
            ],
        }

        url = "{}/chat/completions".format(self._settings.llm_base_url.rstrip("/"))
        headers = {
            "Authorization": "Bearer {}".format(self._settings.llm_api_key),
            "Content-Type": "application/json",
        }

        logger.info(
            "Calling LLM audit API. model=%s page_count=%s rule_count=%s",
            self._settings.llm_model,
            len(page_payload),
            len(strategy_payload.get("rules", [])),
        )
        async with httpx.AsyncClient(timeout=300.0, trust_env=False) as client:
            response = await client.post(url, headers=headers, json=request_body)
            response.raise_for_status()
            response_data = response.json()

        choices = response_data.get("choices") or []
        if not choices:
            raise RuntimeError("LLM API returned no choices.")
        content = choices[0].get("message", {}).get("content")
        if not content:
            raise RuntimeError("LLM API response message is empty.")

        parsed = _ModelAuditResponse.model_validate_json(content)
        notes = list(parsed.notes)
        notes.append("Audit generated by LLM API.")
        logger.info("LLM audit API completed. result_count=%s notes_count=%s", len(parsed.results), len(parsed.notes))
        return parsed.results, notes
